### ISSUE TITLE
Change error message associated with same customization name

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#225]
WHO: Sylvia

The current message reads:

"Customizer with this name, project, version, proxy, already exists"

It should read something like this:

"Customization with this name already exists. Please choose name."  Note the period at the end.

**Comment by allynt** [comment]
Yikes.  This is a real error.  Currently if a user saves a customization w/ the same name an exception is raised.

**Comment by allynt** [comment]
Turns out that in the event that a model customization was invalid, the other customizations (categories & properties) still attempted to be saved.  This is as it should be, and there are try/catch blocks checking if the reason for failing to save a category or property is that the parent model is None - in which case that property or category isn't saved and the checks continue.  This was all working.  However, in the "create-a-property-from-a-json-representation" function, there was an assert statement checking if the property's category is None.  Well, if the parent model was invalid then the category would never have been created which means of course it will be None.  The offending assert has been removed in e2d3ecdc84f169340fb3f3d5f414a3ea088652b0.

**Comment by allynt** [comment]
Oh, and the error message was made clearer as originally requested.
